name: uibakery
"on":
    push:
        branches:
            - main
    workflow_dispatch: {}
env:
    ACR_RESOURCE_GROUP: dt_kube_group
    AZURE_CONTAINER_REGISTRY: acrworkflow1714547000763
    CLUSTER_NAME: dt_kube
    CLUSTER_RESOURCE_GROUP: dt_kube_group
    CONTAINER_NAME: image-workflow-1714547000763
    DEPLOYMENT_MANIFEST_PATH: |
        ./kubernetes/namespace.yaml
        ./kubernetes/ui-bakery-automation.yaml
        ./kubernetes/ui-bakery-backend.yaml
        ./kubernetes/ui-bakery-bakery-front.yaml
        ./kubernetes/ui-bakery-configmap.yaml
        ./kubernetes/ui-bakery-database.yaml
        ./kubernetes/ui-bakery-datasource.yaml
        ./kubernetes/ui-bakery-gateway.yaml
        ./kubernetes/ui-bakery-internal-database.yaml
        ./kubernetes/ui-bakery-python-runtime.yaml
        ./kubernetes/ui-bakery-workbench-front.yaml
jobs:
    buildImage:
        permissions:
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2
              name: Azure login
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            - name: Build and push image to ACR
              run: az acr build --image ${{ env.CONTAINER_NAME }}:${{ github.sha }} --registry ${{ env.AZURE_CONTAINER_REGISTRY }} -g ${{ env.ACR_RESOURCE_GROUP }} -f ./docker-compose-azure-container-instances.yml ./
    deploy:
        permissions:
            actions: read
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        needs:
            - buildImage
        steps:
            - uses: actions/checkout@v3
            - uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2
              name: Azure login
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            - uses: azure/use-kubelogin@v1
              name: Set up kubelogin for non-interactive login
              with:
                kubelogin-version: v0.0.25
            - uses: azure/aks-set-context@v3
              name: Get K8s context
              with:
                admin: "false"
                cluster-name: ${{ env.CLUSTER_NAME }}
                resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
                use-kubelogin: "true"
            - uses: Azure/k8s-deploy@v4
              name: Deploys application
              with:
                action: deploy
                images: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }}
                manifests: ${{ env.DEPLOYMENT_MANIFEST_PATH }}
                namespace: namespace-workflow-1714547000763
